### ISSUE TITLE
Error while testing 2dbat

### ISSUE THREAD

**Issue by KshitijT** [seheonoh/2dbat#2]
I get the following error while running 2dbat (docker) for the test data provided:
```
awk: cannot open paincl.order.txt (No such file or directory)
awk: cannot open paincl.order.txt (No such file or directory)
awk: cannot open paincl.order.txt (No such file or directory)
awk: cannot open paincl.order.txt (No such file or directory)
WARNING:root:Deprecation Warning: 'triangle' has been renamed to 'corner'. This shim should continue to work but you should use 'import corner' in new code. https://github.com/dfm/corner.py
Traceback (most recent call last):
  File "/home/bat/2dbat_dc/pyplots/multinestplot.full.py", line 54, in <module>
    bspline_nbreak_pa = int(args[4])
ValueError: invalid literal for int() with base 10: 'incl'
mv: cannot stat './demo.png': No such file or directory
WARNING:root:Deprecation Warning: 'triangle' has been renamed to 'corner'. This shim should continue to work but you should use 'import corner' in new code. https://github.com/dfm/corner.py
Traceback (most recent call last):
  File "/home/bat/2dbat_dc/pyplots/multinestplot.dirty.py", line 54, in <module>
    bspline_nbreak_pa = int(args[4])
ValueError: invalid literal for int() with base 10: 'incl'
mv: cannot stat './demo.png': No such file or directory
Traceback (most recent call last):
  File "/home/bat/2dbat_dc/pyplots/wallaby2dtr.py", line 220, in <module>
    output = read_2dtrfitFile(trfits)
  File "/home/bat/2dbat_dc/pyplots/wallaby2dtr.py", line 52, in read_2dtrfitFile
    Reader=asciitable.NoHeader, delimiter='\t')
  File "/home/bat/.local/lib/python2.7/site-packages/asciitable/ui.py", line 134, in read
    dat = reader.read(table)
  File "/home/bat/.local/lib/python2.7/site-packages/asciitable/core.py", line 841, in read
    self.lines = self.inputter.get_lines(table)
  File "/home/bat/.local/lib/python2.7/site-packages/asciitable/core.py", line 157, in get_lines
    table = open(table, 'r').read()
IOError: [Errno 2] No such file or directory: '/home/bat/2dbat_proc/wdir/2dbat_output/IA2.40B8X120X20C00S0P45I40DO0.SS92.b6.decim10.fits.h3gfit.x.fits.trfit.dat'
```

I am missing a file or a step here?

**Comment by 3rico** [comment]
Adding a number, e.g 0, at the end of the 2dbat input parameters seemed to solve the problem, not sure which parameter it stands for, makes sure all the input parameters are about 48 in total.
